from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum


class SceneStatus(str, Enum):
    DRAFT = "draft"
    GENERATED = "generated"
    LOCKED = "locked"


class Scene(BaseModel):
    scene_id: str = Field(..., description="Unique identifier for the scene")
    order: int = Field(..., description="Order of the scene in the video")
    narration: str = Field(..., description="Narration text for the scene")
    visual_prompt: str = Field(..., description="Prompt for image generation")
    duration_sec: float = Field(..., description="Duration of the scene in seconds")
    camera_motion: Optional[str] = Field(None, description="Camera motion description (e.g., slow zoom, pan left)")
    image_path: Optional[str] = Field(None, description="File path to generated image")
    audio_path: Optional[str] = Field(None, description="File path to generated audio")
    status: SceneStatus = Field(SceneStatus.DRAFT, description="Status of the scene")


class ProductionStatus(str, Enum):
    DRAFT = "draft"
    GENERATING = "generating"
    READY_FOR_REVIEW = "ready_for_review"
    APPROVED = "approved"


class Production(BaseModel):
    id: str = Field(..., description="Unique identifier for the production")
    topic: str = Field(..., description="Topic of the video")
    format: str = Field(..., description="Format: 'short' or 'long'")
    language: str = Field(..., description="Language: 'en' or 'ta'")
    title: str = Field(..., description="Title of the video")
    full_script: str = Field(..., description="Full script generated by the script agent")
    scenes: List[Scene] = Field(..., description="List of scenes")
    video_prompt: Optional[str] = Field(None, description="Final video prompt for AI video tools")
    status: ProductionStatus = Field(ProductionStatus.DRAFT, description="Overall production status")
    created_at: datetime = Field(default_factory=datetime.now, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.now, description="Last update timestamp")

    # Optional: checkpoint data for resuming
    checkpoint_data: Optional[dict] = Field(None, description="Optional checkpoint data for resuming")